### PR TITLE
v1.5

### PR DESCRIPTION
**Pull request by JustinFreitas**
v1.5 - Include TurnTimer concepts where it starts/resets the timer on each actor's turn.  Added support for a localhost based URL (http://localhost:1803) instead of the default web based URL. If it's not present, the resolution of the timer will only be 4sec, which seems to be the timeout.  I made a simple node app as a host and it worked great, even at 500ms.  That file is included as delayed-response.js and can be run via Node with the command 'node delayed-response.js'.  Options for chat output (enabled by default) , hiding non-friendly when chat enabled (enabled by default), and the URL used for the timer (original is default, localhost:1803 is option).

Local Server via delayed-response.js:
image

### CODE REVIEW

**Comment by mattekure** [comment]
I just wanted to let you know I am seeing these commits come through and I really appreciate them.  I am running a little behind, but I will be reviewing them and push a release once I am comfortable with it.  Thanks!

**Comment by JustinFreitas** [comment]
> I just wanted to let you know I am seeing these commits come through and I really appreciate them. I am running a little behind, but I will be reviewing them and push a release once I am comfortable with it. Thanks!

Yeah, no rush...  take your time with it.  Heck, if it's not what you were thinking and prefer I keep separate, say that too.  I tried to make everything optional.  Happy to do a show and tell if you need.  I think you'll like the localhost stuff.

**Comment by mattekure** [comment]
I'm fairl

> > I just wanted to let you know I am seeing these commits come through and I really appreciate them. I am running a little behind, but I will be reviewing them and push a release once I am comfortable with it. Thanks!
> 
> Yeah, no rush... take your time with it. Heck, if it's not what you were thinking and prefer I keep separate, say that too. I tried to make everything optional. Happy to do a show and tell if you need. I think you'll like the localhost stuff.

I'm fairly certain the Forge will not allow me to include the .js files.  Those would likely have to be linked for download on the forum link.

**Comment by JustinFreitas** [comment]
Ok, whatever you think is best.  If you want me to keep it separate, that's fine too.  I've been loving the timer in my games.  Just having it display the turn time has been helping my players to strive to be more efficient with their turns.  Thanks a bunch.

**Comment by mattekure** [comment]
In testing I noticed this behavior.  If the "Chat: Output Time" option is set to ON, and the "CT: Reset Timer On Turn" is set to OFF, then no time is output in the chat when the turn is passed.   Is that intended behavior?  Logically it seems it should still output the elapsed time which would of course require that you remember the start time somewhere.  I can see this being useful when the GM wants to keep the timer incrementing for the entire combat length to track that, and also wants to know the time per turn for the actors.

Is this intended behavior?

**Comment by JustinFreitas** [comment]
> In testing I noticed this behavior. If the "Chat: Output Time" option is set to ON, and the "CT: Reset Timer On Turn" is set to OFF, then no time is output in the chat when the turn is passed. Is that intended behavior? Logically it seems it should still output the elapsed time which would of course require that you remember the start time somewhere. I can see this being useful when the GM wants to keep the timer incrementing for the entire combat length to track that, and also wants to know the time per turn for the actors.
> 
> Is this intended behavior?

Seems like an easy enough change.  I'll make that.

**Comment by JustinFreitas** [comment]
Ok, that's in.  Yeah, originally, I was thinking that it didn't make too much sense for a shared timer on everyone's turn... but when you said it, my brain started working right and it made total sense.  Thanks!

**Comment by mattekure** [comment]
Add Turn Timer code from Justin.

**Comment by mattekure** [comment]
Hmm, I merged this commit in.  But now when showing the turn timer on passing the turn, it shows the elapsed time since the timer was started, and not the elapsed time since the turn started.  The start of turn time needs to be recorded somewhere in the CT entry, and calculated at the end.  rather then relying on the underlying timer being reset.

**Comment by JustinFreitas** [comment]
Oh, I see what you mean.  That change is more than a conditional update so I'd need a few more minutes.  You gonna revert or you want me to branch anew?

**Comment by mattekure** [comment]
> Oh, I see what you mean. That change is more than a conditional update so I'd need a few more minutes. You gonna revert or you want me to branch anew?

I'll revert.  if I can figure it out.  Still fairly new to github :)

**Comment by mattekure** [comment]
I think I reverted it.  but I'm not really sure

**Comment by JustinFreitas** [comment]
> I think I reverted it. but I'm not really sure

Looks like you were successful on the revert.  I've opened a new PR with the changes as you wanted them.  At your leisure, check out the functionality and see if it meets the mark this time.

**Comment by mattekure** [comment]
Its been pushed live on the Forge.  Thanks again for this great addition!

**Comment by mattekure** [comment]
I edited the forum post and attached the delayed-sponse.js script since it cant be included in the ext.  hopefully what I wrote is all accurate.  https://www.fantasygrounds.com/forums/showthread.php?73977-Timer&p=652131&viewfull=1#post652131

**Pull request merged**
